package utils;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class DealString {
    public static void main(String[] args) {
        String s = "Before solving the 2D problem we first consider a 1D case. The solution is quite simple. Just find the median of all the x coordinates and calculate the distance to the median.\n" +
                "Alternatively, we can also use two pointers to solve the 1D problem. left and right are how many people one left/right side of coordinates i/j. If we have more people on the left we let j decrease otherwise increase i. The time complexity is O(n) and space is O(1).\n" +
                "To be more clear, a better view is that we can think i and j as two meeting points. All the people in [0, i] meet ati and all the people in [j, n - 1] meet at j. We let left = sum(vec[:i+1]), right = sum(vec[j:]), which are the number of people at each meet point, and d is the total distance for the left people meet at i and right people meet at j.\n" +
                "Our job is to let i == j with minimum d.\n" +
                "If we increase i by 1, the distance will increase by left since there are left people at i and they just move 1step. The same applies to j, when decrease j by 1, the distance will increase by right. To make sure the total distance d is minimized we certainly want to move the point with less people. And to make sure we do not skip any possible meet point options we need to move one by one.\n" +
                "For the 2D cases we first need to sum the columns and rows into two vectors and call the 1D algorithm. The answer is the sum of the two. The time is then O(mn) and extra space is O(m+n)";
        s="Since the distance is computed using the Manhattan Distance, we can decompose this 2-d problem into two 1-d problems and combine (add) their solutions. In fact, the best meeting point is just the point that comprised by the two best meeting points in each dimension.";

        s="This problem is an extension of the Two Sum problem. Here, the target is zero. Thus, if a + b + c = 0, then a + b = -c. This essentially reduces this problem to Two Sum.\n" +
                "\n" +
                "Thus, we have to find such triplets whose sum is zero and there should be no duplicates in the answer.\n" +
                "\n" +
                "Approach\n" +
                "The naive approach is to check for each possible triplet. This can be done via three nested loops which will make the time complexity proportional to the third power of the number of elements in the array i.e., O(n3).\n" +
                "\n" +
                "Can we do better \uD83E\uDD14? We can use two pointer trick as follows -\n" +
                "\n" +
                "Sort the array (in time O(n * log(n))).\n" +
                "Now for each element i, do the following steps\n" +
                "Set two pointers left — j = i + 1 and right — k = nums.length - 1.\n" +
                "Check if nums[i] + nums[j] + nums[k] == 0 and if it is zero, add these three numbers to the resultant list.\n" +
                "If the sum nums[i] + nums[j] + nums[k] < 0, this means we can move left pointer forward because since the array is sorted and the sum is less than zero, therefore, it makes sense to check for greater value to make the sum bigger.\n" +
                "If the sum nums[i] + nums[j] + nums[k] > 0, this means we are too right and can move the right pointer backward because since the array is sorted and the sum is greater than zero, therefore, it makes sense to check for smaller value to make the sum lesser.\n" +
                "In between loops, we also need to make sure that we are not checking for duplicate values.\n" +
                "Time Complexity\n" +
                "We are scanning the entire array keeping one element fixed. We are doing this for every element in the array. Thus, we are scanning each element of array n number of times. And we are doing this for n times, hence the worst case time complexity will be O(n2 + n * log n) which comes down to O(n2).\n" +
                "\n" +
                "Space Complexity\n" +
                "We are not using any data structure for the intermediate computations, hence the space complexity is O(1).";

        s="18.Do you have the qualifications and personal characteristics necessary for success in your\n"
            + "chosen career?\n"
            + "I believe I have a combination of qualities to be successful in this career. First, I have a strong\n"
            + "interest, backed by a solid, well-rounded, state-of-the-art education, especially in a career that is\n"
            + "technically oriented. This basic ingredient, backed by love of learning, problem-solving skills,\n"
            + "well-rounded interests, determination to succeed and excel, strong communication skills, and the\n"
            + "ability to work hard, are the most important qualities that will help me succeed in this career. To\n"
            + "succeed, you also need a natural curiosity about how systems work -- the kind of curiosity I. From 1point 3acres bbs\n"
            + "demonstrated when I upgraded my two computers recently. Technology is constantly changing,\n"
            + "so you must a fast learner just to keep up or you will be overwhelmed. All of these traits combine\n"
            + "to create a solid team member in the ever-changing field of information systems. I am convinced\n"
            + "that I possess these characteristics and am ready to be a successful team member for your firm.\n"
            + "19.What are your weak points?\n"
            + "Don’ t say you have one, but give one that is really a “ positive in disguise.” I am sometimes\n"
            + "impatient and do to much work myself when we are working against tight deadlines.” Or “I\n"
            + "compliment and praise my staff, but feel I can improve.”\n"
            + "20.What personal weakness has caused you the greatest difficulty in school or on the job?\n"
            + "My greatest weakness had been delegation. I would take it upon myself to do many small\n"
            + "projects throughout my shift as a manager that could have been done by others in an attempt to\n"
            + "improve my workers' efficiency. Once I realized that I was doing more work than the other\n"
            + "assistant managers, and they were achieving better results, I reevaluated what I was doing. I\n"
            + "quickly realized that if I assigned each person just one small project at the beginning of their shift,\n"
            + "clearly state expectations for the project, and then follow up that everything would get done, and\n"
            + "I could manage much more efficiently and actually accomplish much more.\n"
            + "21.How has your education prepared you for your career?\n"
            + "This is a broad question and you need to focus on the behavioral examples in your educational\n"
            + "background which specifically align to the required competencies for the career.\n"
            + "An example: “ My education has focused on not only the learning the fundamentals, but also on\n"
            + "the practical application of the information learned within those classes. For example, I played a\n"
            + "lead role in a class project where we gathered and analyzed best practice data from this industry.-baidu 1point3acres\n"
            + "Let me tell you more about the results . . .”\n"
            + "Focus on behavioral examples supporting the key competencies for the career. Then ask if they\n"
            + "would like to hear more examples.\n"
            + "As you will note on my resume, I've taken not only the required core classes in the _____ field,\n"
            + "I've also gone above and beyond. I've taken every class the college has to offer in the field and\n"
            + "also completed an independent study project specifically in this area. But it's not just taking the\n"
            + "classes to gain academic knowledge I've taken each class, both inside and outside of my major,\n"
            + "with this profession in mind. So when we're studying _____ in _____, I've viewed it from the\n"
            + "perspective of _____. In addition, I've always tried to keep a practical view of how the\n"
            + "information would apply to my job. Not just theory, but how it would actually apply. My capstone\n"
            + "course project in my final semester involved developing a real-world model of _____, which is\n"
            + "very similar to what might be used within your company...\n"
            + "22.Have you ever had a conflict with a boss or professor? How was it resolved?\n"
            + "Note that if you say no, most interviewers will keep drilling deeper to find a conflict. The key is\n"
            + "how you behaviorally reacted to conflict and what you did to resolve it.\n"
            + "For example: “Yes, I have had conflicts in the past. Never major ones, but there have been\n"
            + "disagreements that needed to be resolved. I've found that when conflict occurs, it helps to fully\n"
            + "understand the other person’ s perspective, so I take time to listen to their point of view, and\n"
            + "then I seek to work out a collaborative solution. For example . . .”\n"
            + "Focus your answer on the behavioral process for resolving the conflict and working\n"
            + "collaboratively.\n"
            + "23.If I were to ask your professors to describe you, what would they say?\n"
            + "This is a threat of reference check question. Do not wait for the interview to know the answer.\n"
            + "Ask any prior bosses or professors in advance. And if they ’ re willing to provide a positive\n"
            + "reference, ask them for a letter of recommendation.\n"
            + "Then you can answer the question like this:\n"
            + "“I believe she would say I'm a very energetic person, that I’ m results oriented and one of the\n"
            + "best people she has ever worked with. Actually, I know she would say that, because those are her\n"
            + "very words. May I show you her letter of recommendation?”\n"
            + "So be prepared in advance with your letters of recommendation.\n"
            + "24.Tell me about a time when you had to plan and coordinate a project from start to finish.\n"
            + "I headed up a project which involved customer service personnel and technicians. I organized a\n"
            + "meeting to get everyone together to brainstorm and get his or her input. From this meeting I\n"
            + "drew up a plan, taking the best of the ideas. I organized teams, balancing the mixture of technical\n"
            + "and non-technical people. We had a deadline to meet, so I did periodic checks with the teams.\n"
            + "After three weeks, we were exceeding expectations, and were able to begin implementation of\n"
            + "the plan. It was a great team effort, and a big success. I was commended by management for my\n"
            + "leadership, but I was most proud of the team spirit and cooperation which it took to pull it off.\n"
            + "25.Describe a situation where others you were working with on a project disagreed with your\n"
            + "ideas. What did you do?\n"
            + "I was on a project team in a business class in my freshman year in college, The group\n"
            + "brainstormed ideas for the video we were assigned to produce, and everyone but me was leaning\n"
            + "toward an idea that would be easy. I suggested instead an idea that would be more difficult but\n"
            + "would be something different that no other group would be doing. I used my communications\n"
            + "skills to persuade the rest of the group to use my idea. During the project, we really learned what\n"
            + "teamwork was all about, became a close team, and ended up putting a lot of hard work into the\n"
            + "project. All the team members ended up feeling very proud of the video, and they thanked me\n"
            + "for the idea -- for which we earned an A.\n"
            + "26.Why did you choose to attend your college?\n"
            + "My college has always had a reputation as having an excellent accounting department, so I knew\n"
            + "that if I enrolled there, I would achieve first-class preparation for my chosen career field. It is also\n"
            + "a highly accredited school known for satisfying employers with the preparation of its graduates --\n"
            + "that's why companies like yours recruit at my school -- the school produces top graduates. The\n"
            + "school offers an excellent liberal-arts background, which research shows equips graduates with\n"
            + "numerous qualities, such as versatility and strong critical-thinking skills. Finally, having visited the\n"
            + "campus before enrolling, I knew that the business school emphasized group projects. During my\n"
            + "four years in the school, I participated in more than 35 group projects, which taught me\n"
            + "invaluable teamwork, communication, and interpersonal skills.. From 1point 3acres bbs\n"
            + "27.What changes would you make at your college?\n"
            + "My major department had a wonderful internship program, and I was able to complete three\n"
            + "valuable internships with my department's guidance. Some other departments in the business\n"
            + "school don't have internship programs that are as strong as my department's. I'd like to see all\n"
            + "the departments have strong internship programs so all my school's business grads would have\n"
            + "the same opportunities that I had.\n"
            + "28.How will the academic program and coursework you've taken benefit your career?\n"
            + "As you will note on my resume, I've taken not only the required core classes for the finance field,\n"
            + "I've also gone above and beyond by double majoring in accounting. I doubled majored since I\n"
            + "knew that the financial consulting field requires much knowledge of portfolio analysis and. check 1point3acres for more.\n"
            + "understanding of the tax laws. I believe that my success in both areas of study have specifically\n"
            + "prepared me for this area. But it's not just taking the classes in these two areas that allow me to\n"
            + "offer Merrill Lynch clients more. I minored in Spanish to understand the growing Hispanic\n"
            + "clientele in the Central Florida area, which as you are well aware, is a growing source of revenue\n"
            + "for the industry. If you like, I can elaborate on other aspects of my education further.\n"
            + "29.What were your favorite classes? Why?. From 1point 3acres bbs\n"
            + "My favorite classes have been the ones pertaining to my major, which is marketing. These classes\n"
            + "have laid the groundwork for my career in marketing. They have also taught me skills that I can\n"
            + "bring to my employer, ranging from communication skills to interacting with others.\n"
            + "30. Do you enjoy doing independent research?\n"
            + "Are you the type of student for whom conducting independent research has been a positive\n"
            + "experience?\n"
            + "Yes, I love it. I thoroughly enjoyed my senior research in college while many others in my class\n"
            + "were miserable. I was never tired of learning more about my topic and found it exhilarating to be\n"
            + "researching something that had not been studied before.\n"
            + "31.Who were your favorite professors? Why? Describe the type of professor that has created the\n"
            + "most beneficial learning experience for you.\n"
            + "My favorite professors were the ones who gave me hands-on learning experiences that I can\n"
            + "apply to my career. Any person can make you memorize the quadratic equation, but someone. 1point3acres\n"
            + "who can show you how to use it, and why, were the professors I liked. I liked teachers who\n"
            + "realized that sometimes there is more then one answer and everyone thinks differently.\n"
            + "32.Why is your GPA not higher? Do you think that your grades are a indication of your academic\n"
            + "achievement?\n"
            + "I have focused much of my energy on work and obtaining real-world experience. I commend my\n"
            + "classmates who have earned high GPAs, but I also feel it's important to be well-rounded. In\n"
            + "addition to work experience, I participated in sports and extracurricular activities in school. These\n"
            + "activities taught me leadership, communication, and teamwork skills. Sometimes my heavy load\n"
            + "has not allowed me to keep up with some of my studies, but I have learned an enormous amount\n"
            + "that I can apply in my future industry. As you will discover if you talk to my supervisors, my ability\n"
            + "to work effectively is much more reflective of my future potential than is my GPA.\n"
            + "33.Do you have any plans for further education? What plans do you have for continued study? An\n"
            + "advanced degree?\n"
            + "I plan to continue my education for the rest of my life. In any technology-related field, keeping up\n"
            + "to date through continuing education is of the utmost importance. Continuing education can\n"
            + "include on-the-job training, courses sponsored by the employer, and courses taken in new\n"
            + "technologies as they emerge. I plan to be not only a career employee but a career student so that\n"
            + "I can be the best information systems analyst I can be. I will ensure, however, that any education I\n"
            + "pursue not only doesn't interfere with my job or the company's policies, but will enhance my\n"
            + "value as an employee.\n"
            + "34.Give an example of how you applied knowledge from previous coursework to a project in\n"
            + "another class.\n"
            + "Last semester I was taking a microeconomics and a statistics course. One of the microeconomics\n"
            + "projects dealt with showing the relationship between the probability that customers would stop\n"
            + "buying a product if the price was raised a certain amount. Through what I learned in statistics I\n"
            + "could find the median where the price was the highest and still kept most of the customers\n"
            + "happy.\n"
            + "35. Describe a situation in which you found that your results were not up to your professor's or\n"
            + "supervisor's expectations. What happened? What action did you take?\n"
            + "Recently I was asked to put together a proposal for a migration of network systems.\n"
            + "Misunderstanding my boss, I thought it was just an informal paper. When I presented it to him\n"
            + "days later, he was upset with the quality since it had to be presented to our VP. I explained my\n"
            + "misunderstanding, apologized, reworked the paper, and had it back to him with enough time for\n"
            + "him to review it before he presented it successfully at the meeting\n"
            + "36.What do you know about our organization?\n"
            + "Research the target company before the interview. Basic research is the only way to prepare for\n"
            + "this question. Do your homework, and you’ ll score big on this question. Talk about products,\n"
            + "services, history and people, especially any friends that work there. “ But I would love to know\n"
            + "more, particularly from your point of view. Do we have time to cover that now?\n"
            + "This question is one reason to do some research on the organization before the interview. Find\n"
            + "out where they have been and where they are going. What are the current issues and who are\n"
            + "the major players?\n"
            + "37.What experience do you have?\n"
            + "Try to cite experience relevant to the company’ s concerns. Also, try answering these questions\n"
            + "with a question: “ Are you looking for overall experience or experience in some specific area of\n"
            + "special interest to you?” Let the interviewer’ s response guide your answer.\n"
            + "What experience do you have in this field? Speak about specifics that relate to the position you\n"
            + "are applying for. If you do not have specific experience, get as close as you can.\n"
            + "I think I have my current job because of my experiences abroad. Those experiences gave me\n"
            + "greater self-confidence and a greater understanding of myself, which led to my willingness to\n"
            + "uproot myself and try new work in a new location.”\n"
            + "38.According to your definition of success, how successful have you been so far?\n"
            + "Be prepared to define success, and then respond (consistent record of responsibility)\n"
            + "You should always answer yes and briefly explain why. A good explanation is that you have set\n"
            + "goals, and you have met some and are on track to achieve the others.\n"
            + "39. How has your college experience prepared you for a business career?\n"
            + "Emphasize your best and favorite subjects. If grades were average, talk about leadership or jobs\n"
            + "you took to finance your education. Talk about extra-curricular activities (clubs, sports, volunteer\n"
            + "work)\n"
            + "I have prepared myself to transition into the the work force through real-world experience\n"
            + "involving travel abroad, internship, and entrepreneurial opportunities. While interning with a\n"
            + "private organization in Ecuador, I developed a 15-page marketing plan composed in Spanish that\n"
            + "recommended more effective ways the company could promote its services. I also traveled\n"
            + "abroad on two other occasions in which I researched the indigenous culture of the Mayan Indians\n"
            + "in Todos Santos, Guatemala, and participate din a total language immersion program in Costa\n"
            + "Rica. As you can see from my academic, extracurricular, and experiential background, I have\n"
            + "unconditionally committed myself to success as a marketing professional.\n"
            + "40.What do you look for in a job?\n"
            + "Flip this one over. Despite the question, the employer isn ’ t really interested in what you are\n"
            + "looking for. He’ s interested in what he is looking for. Address his interests, rather than yours. Use\n"
            + "words like “ contribute,”“ enhance,”“ improve,” and “ team environment.” Fit your answer\n"
            + "to their needs Relate your preferences and satisfiers/dissatisfiers to the job opening.\n"
            + "41. How long would you stay with us?\n"
            + "“ As long as I feel that I’ m contributing, and that my contribution is recognized. I’ m looking to\n"
            + "make a long term commitment.”\n"
            + "Specifics here are not good. Something like this should work: I’ d like it to be a long time. Or As\n"
            + "long as we both feel I’ m doing a good job.\n"
            + "42. What kinds of people do you find difficult to work with?\n"
            + "Use this question as a chance to show that you are a team player: “The only people I have\n"
            + "trouble with are those who aren ’ t team players, who just don ’ t perform, who complain\n"
            + "constantly, and who fail to respond to any efforts to motivate them. ” The interviewer is\n"
            + "expecting a response focused on personality and personal dislikes. Surprise her by delivering an\n"
            + "answer that reflects company values.\n"
            + "43. Why do you want to work for us?\n"
            + "You feel you can help achieve the companies’ objectives, especially in the short run. You like\n"
            + "what you’ ve learned about the company, its policies, goals and management: “ I’ ve researched\n"
            + "the company and people tell me it’ s a good place to work.”\n"
            + "This may take some thought and certainly, should be based on the research you have done on the\n"
            + "organization. Sincerity is extremely important here and will easily be sensed. Relate it to your\n"
            + "long-term career goals.\n"
            + "44. Describe some situations in which you have worked under pressure or met deadlines?\n"
            + "Refer to accomplishments. Everyone has had a few of these pressure situations in a career.\n"
            + "Behavior-related questions aim at assessing a candidate’ s character, attitude, and personality\n"
            + "traits by asking for an account of how the candidate handled certain challenging situations. Plan\n"
            + "for such questions by making a list of the desirable traits relevant to the needs of the industry or\n"
            + "prospective employer and by preparing some job-related stories about your experience that\n"
            + "demonstrate a range of those traits and habits of conduct. Before answering the questions, listen\n"
            + "carefully and ask any clarifying questions you think necessary. Tell your story and conclude by\n"
            + "explaining what you intended your story to illustrate. Finally, ask for feedback:“ Does this tell you\n"
            + "what you need to know?”\n"
            + "You may say that you thrive under certain types of pressure. Give an example that relates to the\n"
            + "type of position applied for.\n"
            + "45. Why haven’ t you found a new position before now?\n"
            + "“ Finding the right job takes time. I’ m not looking for just any job.”\n"
            + "46.How much do you expect if we offer this position to you?\n"
            + "Be careful. If you don’ t know the market value, return the question by saying that you would\n"
            + "expect a fair salary based on the job responsibilities, your experience and skills and the market\n"
            + "value of the job. Express your interest in the job because it fits your career goals – Receptive to\n"
            + "a reasonable and competitive offer – don’t talk $’s. ANSWER: I’m open to a competitive offer.\n"
            + "I’ d prefer to discuss the opportunity and allow my recruiter to handle any salary questions.\n"
            + "47.Tell me about your dream job\n"
            + "Stay away from a specific job. You cannot win. If you say the job you are contending for is it, you\n"
            + "strain credibility. If you say another job is it, you plant the suspicion that you will be dissatisfied\n"
            + "with this position if hired. The best is to stay genetic and say something like: A job where I love\n"
            + "the work, like the people, can contribute and can’ t wait to get to work.\n"
            + "48. How do you propose to compensate for your lack of experience?\n"
            + "First, if you have experience that the interviewer does not know about, bring that up: Then, point\n"
            + "out (if true) that you are a hard working quick learner.\n"
            + "49.Why should I hire you?\n"
            + "The easy answer is that you are the best person for the job. And don’ t be afraid to say so. But\n"
            + "then back it up with what specifically differentiates you.\n"
            + "For example: “ You should hire me because I’ m the best person for the job. I realize that there\n"
            + "are likely other candidates who also have the ability to do this job. Yet I bring an additional\n"
            + "quality that makes me the best person for the job--my passion for excellence. I am passionately\n"
            + "committed to producing truly world class results. For example . . .”\n"
            + "Are you the best person for the job? Show it by your passionate examples.\n"
            + "This may sound suspicious, negative, or just plain harsh. Actually, it ’ s a call for help. The\n"
            + "employer wants you to help him/her hire you. Keep your response brief. Recap any job\n"
            + "requirements the interviewer may have mentioned earlier in the interview, then, point by point,\n"
            + "match your skills, abilities and qualifications to those items. Relate a past experience which\n"
            + "represents success in achieving objectives which may be similar to those of the prospective\n"
            + "employer.\n"
            + "I sincerely believe that I'm the best person for the job. I realize that there are many other college\n"
            + "students who have the ability to do this job. I also have that ability. But I also bring an additional\n"
            + "quality that makes me the very best person for the job -- my attitude for excellence. Not just\n"
            + "giving lip service to excellence, but putting every part of myself into achieving it. In college and at\n"
            + "my previous jobs, I have consistently reached for becoming the very best I can become. I think my\n"
            + "leadership awards from my college, and my management positions are the result of possessing\n"
            + "the qualities you're looking for in an employee.. From 1point 3acres bbs\n"
            + "50. What qualities do you feel a successful manager should have?\n"
            + "Focus on two words: leadership and vision.\n"
            + "Here is a sample of how to respond: “The key quality in a successful manager should be\n"
            + "leadership--the ability to be the visionary for the people who are working under them. The\n"
            + "person who can set the course and direction for subordinates. The highest calling of a true leader\n"
            + "is inspiring others to reach the highest of their abilities. I'd like to tell you about a person whom I\n"
            + "consider to be a true leader . . .”\n"
            + "Then give an example of someone who has touched your life and how their impact has helped in\n"
            + "your personal development.\n"
            + "A successful manager should have the vision and capabilities to formulate strategies to reach his\n"
            + "or her objectives and communicate these ideas to his or her team members. In addition to\n"
            + "serving as a positive role model for co-workers, successful managers must also be capable of-baidu 1point3acres\n"
            + "inspiring others to recognize, develop, and apply their talents to their utmost potential to reach a\n"
            + "common goal. These are the traits I hope to demonstrate when I'm a manager.\n"
            + "51. What is your most important accomplishment to date?\n"
            + "It is important when answering this question to focus on an accomplishmentthat highlights the\n"
            + "skills needed to be successful in the specific position youare applying for. For instance, when\n"
            + "interviewing for an investment researchassociate or assistant position it is important to mention\n"
            + "an accomplishment that required keen quantitative skills, problem solving ability and success asa\n"
            + "team member. Be sure when answering this question that you providetangible and measurable\n"
            + "results to your accomplishment.\n"
            + "52. Why did you choose this career?\n"
            + "I chose medicine because I loved science. Even when I was very young, I was completely\n"
            + "enamored with doctors--how they cared about other people, especially people who were sick\n"
            + "and hurting. Anesthesiology has allowed me to combine my interests and continues to keep me\n"
            + "challenged.\n"
            + "My past experiences have shown me that I enjoy facing and overcoming the challenge of making\n"
            + "a sale. Without a doubt, once I have practiced my presentation and prepared myself for\n"
            + "objections, I feel very confident approaching people I don't know and convincing them that they\n"
            + "need my product. Lastly, I like sales because my potential for success is limited only by how much\n"
            + "of myself I dedicate toward my goal. If any profession is founded on self-determinism, it surely\n"
            + "must be sales.\n"
            + "53. What is your salary expectation for this job?\n"
            + "I’ ll need more information about the job and the responsibilities involved before we can begin to\n"
            + "discuss salary. Can you give me an idea of the range budgeted for this position?”\n"
            + "54. How do you keep current and informed about your job and the industries that you have\n"
            + "worked in?\n"
            + "Pride myself on my ability to stay on top of what is happening in my industry. I do a lot of reading\n"
            + "– the business section of the newspapers and magazines. I belong to a couple of professional\n"
            + "organizations and network with colleagues at the meetings. I take classes and seminars whenever\n"
            + "they are of interest, or offer new information or technology.\n"
            + "Try to include improvement activities that relate to the job. A wide variety of activities can be\n"
            + "mentioned as positive self-improvement. Have some good ones handy to mention.\n"
            + "55. When have you been most satisfied in your career?\n"
            + "The job before the one I am currently at was my most rewarding experience for me. I worked in a\n"
            + "wonderful team environment. There was a lot of camaraderie. I worked with a team of four\n"
            + "people and we did some really original thinking. It is that kind of environment I want to be\n"
            + "involved in again.\n"
            + "56. Why do you want this job?\n"
            + "I’ ve been very careful about the companies where I have applied. When I saw the ad for this\n"
            + "position, I knew I found what I was looking for. What I can bring to this job is my seven years of\n"
            + "experience, and knowledge of the industry, plus my ability to communicate and build customer\n"
            + "relationships. That, along with my flexibility and organizational skills, makes me a perfect match\n"
            + "for this position. I see some challenges ahead of me here, and that’ s what I thrive on. I have\n"
            + "what you need, and you have what I want.\n"
            + "I am convinced that there would be no better place to work than Accenture. You are the top\n"
            + "consulting firm in the United States. You provide your employees with the tools they need to stay\n"
            + "competitive and sharpen their skills while working in an open, team-based environment. I am\n"
            + "also aware that you provide a mentor for all new employees, and I would embrace any\n"
            + "opportunity to work with a mentor and eventually become one myself.\n"
            + "57. Describe a challenging work issue you had to face, and how you dealt with it?\n"
            + "Consider what would be the requirements of the ‘ new’ job/organization and find something in\n"
            + "your past that highlights a skill, experience or situation that might occur or be needed going\n"
            + "forward. It is always a good idea to make lists in preparation for interviews: New job will need I\n"
            + "can provide Proof/example For your proofs, list (for yourself) examples of when you used the skill,\n"
            + "exhibited the characteristic or handled the problem. This will not only give you ’ short stories’\n"
            + "to relate in an interview, it will also bolster your confidence and target your job search.\n"
            + "58. In what way do you think you can contribute to our company?\n"
            + "Preparing to answer this question requires a 2-step preparation: assessing your skills and\n"
            + "researching the needs of the company. An integral part of skill assessment (looking at your own\n"
            + "experience, education and talents) is to ’ skill-match’ . Considering the job opening, what are the\n"
            + "skills needed? Make a list of the requisite skills (in priority order) and then list concrete examples\n"
            + "of your possession of the skill. For example: a sales representative would need good\n"
            + "interpersonal skills, the ability to deal with difficult people. For ‘ proof’ of this skill, you could\n"
            + "list experiences and examples of how you were successful in a difficult situation. These matched. From 1point 3acres bbs\n"
            + "skills are your key selling points. Next, what appears to be the current problems at the\n"
            + "organization, based upon your research? What are their needs that you can meet? In other words,\n"
            + "given the specifics of the company, what value can you add? After these two steps, you are in a\n"
            + "great position to come up with concrete examples of what you can offer the company. This\n"
            + "question, by the way, is just another version of “ Why should we hire you?” . In the interview,\n"
            + "when asked this question, you could respond with: “ In my experience in sales, I know having the-baidu 1point3acres\n"
            + "ability to deal effectively with all types of people is not merely a positive element — it is an\n"
            + "essential one. With your plans to expand into ____ market, a sales representative with a proven\n"
            + "ability to meet with all types of people and to be able to assess and meet their immediate needs\n"
            + "would be a great asset. In the past __ years, I have increased sales __… ..”\n"
            + "59.Tell me a story.\n"
            + "Many interviewers like to hear ’ stories’ or examples from your work life. So pick something\n"
            + "that is more usual than not (not the day of a plant explosion and you saved 10 lives!) but a story\n"
            + "that shows how you handle yourself, handle difficult people or situations. Can you think on your\n"
            + "feet? Do you adhere to the rules? Consider the type of organization you are aiming at… each\n"
            + "has its own culture. The World Wrestling Federation entertainment culture is different than the\n"
            + "American Bible Society and also different from Amazon.com. Gear your stories to give the listener\n"
            + "a feeling that you could fit in… you could do the job here.\n"
            + "60. Tell us about your analytical skills.\n"
            + "This should be easy if you have done a realistic skill inventory for yourself, listing what skills you\n"
            + "do have and how you can offer proof of this skill (where you learned it, last used it). Working off\n"
            + "your inventory, focus on various analytical skills and match them to the skills you feel are most\n"
            + "important for the job you are considering. You can now give specific examples of skills you can\n"
            + "offer. (Do not neglect skills obtained in extracurricular activities, such as volunteer work.)\n"
            + "61. What can you add to what we have already asked you that should make us want to hire you?\n"
            + "Think grocery shopping… all those brands in the soap aisle begging for your attention. Each one\n"
            + "comes with its own key selling points. Remember the comics, Superman? On TV, he sold\n"
            + "himself… stronger than a locomotive, faster than a speeding bullet, able to leap tall buildings in\n"
            + "a single bound. What are your key selling points? Plan this out ahead of time for the next\n"
            + "interview… or include in a thank you letter for this past interview. Think a 1 minute infomercial-baidu 1point3acres\n"
            + "about yourself. What are your core strengths? Is it communicating with children, being a mentor\n"
            + "to other teachers, being able to keep topics current and interesting… . Think of what is needed\n"
            + "to be successful in the job and how you specifically meet those needs — provide examples.\n"
            + "Increased reading scores by using… Math scores jumped __% due to my … Offer some proof\n"
            + "from your past to support your claims. But it is your ability to assess the situation and analyze. From 1point 3acres bbs\n"
            + "your potential contributions that will sell your candidacy. Do not think it too late — send a\n"
            + "strong thank you and include in your request for the job the key reasons why you are the best\n"
            + "candidate.\n"
            + "62.What does “ customer service” mean to you?\n"
            + "Think of yourself as a customer — what do you expect from salespeople … regardless of the\n"
            + "circumstances and/or the problem. An example may be “Customer service is a two-piece\n"
            + "reaction. First—respect; second — problem solving.” See if that makes sense and if you sound\n"
            + "convincing when you do practice it. If you can give a brief story or two of what you have\n"
            + "witnessed as extraordinary examples of customer service behavior. By using yourself as a focal\n"
            + "point you will be able to enunciate clearly your understanding of customer service.\n"
            + "63. What do you know about our company?\n"
            + "If you can relate your knowledge to the area that you would be involved in, it would show that\n"
            + "already you have an active interest in the organization. For example, if you were interested in\n"
            + "marketing, “ I understand that you are one of the top 10 companies in sales to Europe but are\n"
            + "currently interested in expanding your market into Asia. Competition is keen in that area but you\n"
            + "have an advantage in that you product offers features that others do not, such as… ..” It is not\n"
            + "only showing that you have done the research but also that you like/know what you have learned\n"
            + "about the company and have applied it to how you can add value in the position.\n"
            + "You're large and respected worldwide. You're both a clinical and teaching hospital. Over the last\n"
            + "60 to 70 years you've produced award-winning research. In reviewing your Web site, I've\n"
            + "familiarized myself with many of your corporate goals and objectives.\n"
            + "64. What do you wish to gain from our company?\n"
            + "Excellent question! Research is the answer (know everyone is tired of hearing this but we feel this\n"
            + "is one great way for applicants to make a difference in their candidacy). Determine some of the\n"
            + "key elements in the corporate structure, product base, employees/management team or recent\n"
            + "history. What appeals to you about working at this company? Go with what you know. “ In the\n"
            + "past, I have had opportunities to work on new products being launched. I am very excited about\n"
            + "your plans to start an entire new line of products. With my prior experience I know I can provide\n"
            + "insights and make contributions immediately and I will also learn so much from the excellent\n"
            + "team you have in place. Having done single products, I would love to be in on the give-and-take\n"
            + "meetings planning the new line… there is much I can offer but also much for me to learn.”\n"
            + "Finding something specific… the opportunity to use a new technology, a new skill, to work with\n"
            + "‘ experts on their team”… are ways for you to find job satisfaction, which is another way of\n"
            + "asking this question\n"
            + "65. What do you think the employee's responsibilities are to the company?\n"
            + "As an employee you have several responsibilities to your employer. They are as follows: to\n"
            + "perform a good day’ s work to be loyal to act as part of the team to value the relationship to earn\n"
            + "the employer’ s trust to grow with a passion for the product/service.. check 1point3acres for more.\n"
            + "66. What motivates you?\n"
            + "Other than looking into your past experiences … .Times when you were motivated and times. check 1point3acres for more.\n"
            + "when you were not… no one but you has this answer. Find concrete examples when you had to\n"
            + "pull it all together and get motivated to get the job done; what does it for you?\n"
            + "This is a personal trait that only you can say, but good examples are: Challenge, Achievement, and\n"
            + "Recognition\n"
            + "You would think that because I am interested in sales, only financial compensation would\n"
            + "motivate me to achieve. Although monetary rewards are important to me, I am driven to succeed\n"
            + "internally. More than anything, I want to be respected by my friends and coworkers for being the\n"
            + "best at what I do. Whether I am considered to be the best car detailer in my hometown or the\n"
            + "best columnist for my college newspaper, I want to be recognized as the best.\n"
            + "67. What things make a good team member?\n"
            + "Consider first the situational context of the question. What is the team environment of the\n"
            + "organization that you are interviewing — do they have a strong, organized team-based work\n"
            + "environment or is it based on informal authority and fluctuating teams? Ideally, you should have\n"
            + "had an opportunity to research and ask some questions about the organization to determine how\n"
            + "they operate (and if indeed you want to work in that environment.) Model your responses to the\n"
            + "organization. Obviously, you are describing yourself = good team member. My ideas of what\n"
            + "makes a good team member may be very different from yours—and from the organization. Also\n"
            + "depends on where you are in the team—new member, leader, support. How do you see yourself?\n"
            + "How do you make yourself fit into a new team? How do you elicit cooperation from other team\n"
            + "members? What do you think the organization ’ s biggest problem is relative to teams and\n"
            + "team-building? And, what solution could you provide?\n"
            + "68. Why do you feel we should hire you for this position?\n"
            + "Before you a resume or draft a cover letter and certainly before you go to an interview you\n"
            + "should do 2 things: Research the job and the organization. What do they need? What are the\n"
            + "requirements for the position? What role does this job play in the overall goals of the\n"
            + "organization? Research yourself. What skills and experiences and interests can you offer? How\n"
            + "will you add value to the organization? How can you prove that you have the required skills and\n"
            + "experience needed for the job? Do a skill matching exercise: The organization/job needs...\n"
            + "(skill/experience) and I have it because I did ….. The organization needs….. And i can provide…..\n"
            + "Be certain to have specific examples of how you have added value in the past and be enthusiastic\n"
            + "on how you can add value to this organization. Do not forget … the organization is looking to\n"
            + "solve a problem and you are selling yourself as a solution.\n"
            + "68.What do you expect your starting salary to be?\n"
            + "Discussions of salaries and compensation should not be held until an offer is made. With that\n"
            + "said, let’ s look into the real world when this is not the case most of the time. Employers are\n"
            + "shopping, trying to guess your price tag. This is one of those screening questions used to either\n"
            + "screen in or screen out… so a response is important. Have you done your homework? What is\n"
            + "the price for this job in the marketplace? Have you checked out classified ads or online ads for\n"
            + "similar positions? Are you within the range, given your level of experience? Pegging yourself\n"
            + "mentally to the right price is the first step. Second step is sharing this information correctly. Do\n"
            + "you have enough information about this new job to determine your salary? If not… state it and\n"
            + "ask for the information that is needed. “Before I can discuss salary, I would like to know the\n"
            + "reporting requirements and how many people I would be supervising. In addition, what are the\n"
            + "skill levels and experience of my staff?” You can also ask “What are others in similar positions\n"
            + "being paid?” When you can no longer stall or seek additional information… “Based on what\n"
            + "you have told me and exclusive of other compensation elements I feel that the position would\n"
            + "warrant a salary range of $_______ to $___________” Name a range such as $40,000 to $45,000\n"
            + "to give both sides some wiggle room and allow for some give-and-take when benefits and other\n"
            + "compensation is considered. If you know what you are willing to accept as salary and what the\n"
            + "market pays, using a salary range should permit you to be negotiable.\n"
            + "70. When did you decide on this career?\n"
            + "I decided to pursue this career while studying art during my freshman and sophomore years in\n"
            + "college. The decision to focus on design came naturally as I took as many of the fine arts and\n"
            + "graphics course electives that the schedule would allow; I really did not have to think about it, it\n"
            + "just happened. I was always interested in art, and found myself much more suited for the\n"
            + "\"structure\" of graphic design versus the fine arts courses I was taking. I always admired\n"
            + "magazines and catalogs for their layout even before I knew much about the profession of graphic\n"
            + "design. Though I enjoy fine arts very much, I found graphic design to be the perfect fit for my half\n"
            + "left brain, half right brain personality!\n"
            + "71.How do you plan to achieve these goals? What specific goals have you established for your\n"
            + "career?\n"
            + "Remember, all goal setting must be immediatly followed by massive and consistent action toward\n"
            + "it's fullfillment. In most cases, setting the goal alone doesn't make it happen, I learned that from\n"
            + "experience.\n"
            + "Good question. I'll try to offer some of the aspects I consider when setting goals for myself...I\n"
            + "mean there are some questions that you should ask yourself in formulating your goals, such as:\n"
            + "- What do I want? (This is usually best stated in the positive. Goals like \"I don't know any more of\n"
            + "the same old crap.\" tend to not be that useful.\n"
            + "- Where am I now in relation to that?\n"
            + "- What specifically do I want and how will I know when I have it? (Be specific in describing what\n"
            + "you want. What will you see, feel, hear when you have accomplished your goal. Who will you be\n"
            + "with? Where will you be? Also make sure that this goal is dis-associated...I'll explain that in a\n"
            + "minute if it's not clear).\n"
            + "- Is it consistent with my values and other goals? (Sometimes people make goals like, I want to be\n"
            + "a coporate executive in a Fortune 500 company AND be home for dinner by 6 o'clock everyday to\n"
            + "spend time with my family. Not saying it couldn't happen, but you might want to outline how\n"
            + "specifically you plan to accomplish it).\n"
            + "- Is accomplishing this goal something I can control? (Who else has to be involved? Are you doing\n"
            + "this for yourself or because of other people?)\n"
            + "- What resources will you need to accomplish the goal? (Do you need money, time, more friends,\n"
            + "special contacts in foreign governments?)\n"
            + "- For what purpose do I want this? Some corrolaries to the last question are: - How else could I\n"
            + "get this same thing? - What will happen if I do get my goal? - What will happen if I don't get my\n"
            + "goal? - What won't happen if I do get my goal? - What won't happen if I don't get my goal?\n"
            + "Okay so there are some questions that are helpful in exploring goals and deciding on what goals\n"
            + "are appropriate and how they will integrate together with other goals into your life. The\n"
            + "important thing for me is to program these into my future using \"Time Lines\". For me I tend to\n"
            + "see the future as a line that shoots off to my right at a 45 degree angle and when I look there I\n"
            + "see the future, the things that WILL happen. And this is quite a different place than where I seem\n"
            + "to keep my hopes...See the things that I keep as hopes are the things I'd like to see happen but\n"
            + "have never quite put in the right place to make it all happen.\n"
            + "Do you see why it's important to distinguish between hopes and your future? Too many people\n"
            + "make goals and then say \"Gosh I sure hope that happens\" and quicker than you can blink all the\n"
            + "representations of their goal have been tossed right into that pile of hopes...and maybe with\n"
            + "incredible luck it will happen, but only because of luck. So I would recommend taking a little\n"
            + "inventory by imagining your future, where are you keeping track of what you know will happen,\n"
            + "the things you are absolutely committed to? And where are you keeping your\n"
            + "hopes/wish-it-would-happens? When you make pictures of these things where do you seem\n"
            + "them? Are there differences in focus, clarity, location? Are there sounds associated with one class\n"
            + "and not the other? What are the differences in the feelings you get with each?\n"
            + "Now decide how important your goal is and make sure that when you imagine that goal that you\n"
            + "mentally sort it into the right place so it's just like the things you know will happen. And make\n"
            + "sure that you are \"dis-associated\" from your goal, that means that you can see it in the future but\n"
            + "aren't actually experiencing it right now.\n"
            + "There are people who habitually fail to achieve there goals for one simple reason, and that is this.\n"
            + "They imagine a really great goal and then they imagine how great it will feel when they\n"
            + "accomplish their goal. Then they step into those great feelings, experience them now, and then\n"
            + "think, \"Gosh that was great, and since I've already had all the pleasure of accomplishing the goal,\n"
            + "I guess I should think about something else.\" So when I say stay disassociated, I mean keep the\n"
            + "feelings out there, make sure your goal is compelling but make sure that you don't allow yourself\n"
            + "to feel the rewards until you've actually got the whole thing. It will help propel you into the\n"
            + "future that you've built.\n"
            + "My goals include becoming a Certified Financial Advisor so I can obtain a better working\n"
            + "knowledge of financial research analysis, which would allow me contribute to my client base as a\n"
            + "better financial consultant since I would have that extra insight into the companies they are\n"
            + "seeking to invest in. Also this is the foundation block to advancing my career to portfolio manager\n"
            + "or even branch office manager.\n"
            + "72.How do you personally define success?\n"
            + "Success: In a career, being good at something you love and believing that your expertise helps\n"
            + "other people. Being aware that hard work AND luck (or blessings — choose your own words)\n"
            + "play a part in any success, being grateful rather than smug.-baidu 1point3acres\n"
            + "In life: Doing your best at your work and in dealing with your family and friends (not necessarily\n"
            + "in that order), but taking time for a few pet projects or dreams of your own. Devoting all of your\n"
            + "time to any one endeavor (be it work, play or raising a family) can never make you successful, just\n"
            + "boring and bored.\n"
            + "Last semester I was hired by by university's Council for Student Activities. The group negotiates\n"
            + "contracts of entertainers, sets up sound equipment, markets the entertainers to students, and\n"
            + "generally decides what kind of programming should be done. When I got hired, I didn't know the\n"
            + "first thing about how fill any of those responsibilities. I decided, however, that I wasn't going to\n"
            + "fail. Four months later, I have become the Webmaster for the group. I also write our campus\n"
            + "newsletter and created Game Night, a student competition of table games. That event yielded\n"
            + "the biggest audience ever for a non-concert event.\n"
            + "73.What will it take to attain your goals, and what steps have you taken toward attaining them?\n"
            + "I've already done some research on other workers at Merrill Lynch to see how they achieved\n"
            + "similar goals. I know that Merrill Lynch encourages the pursuit and will reimburse for tuition of a\n"
            + "graduate degree. I plan on pursuing a MBA to give me an even more extensive knowledge of\n"
            + "business and financial analysis.\n"
            + "74.Describe a situation in which you were successful.. 1point3acres\n"
            + "75.What do you think it takes to be successful in this career?. check 1point3acres for more.\n"
            + "I believe successful salespeople put forth that extra effort that turns potential clients into\n"
            + "first-time customers. Salespeople who attend to the details by doing whatever it takes to win\n"
            + "over a prospective customer distinguish themselves from the countless others who don't go to\n"
            + "any extra effort. Second, I think that if you label success as an attainable goal, you will never\n"
            + "consistently remain successful. You can only succeed if you learn all there is to learn about your\n"
            + "product, your competitors, and personal selling. Since this learning process is continuous, it's an\n"
            + "unattainable goal. With good reason, salespeople should not consider success an attainable\n"
            + "ending point but an objective that will always linger slightly beyond their reach.\n"
            + "76.What accomplishments have given you the most satisfaction in your life?\n"
            + "77.How would you describe yourself in terms of your ability to work as a member of a team?\n"
            + "I have had many opportunities in both athletics and academics to develop my skills as a team\n"
            + "player. My tenure as a rower with my college's crew team serves as a good example. I learned a\n"
            + "great deal about teamwork while rowing because all the rowers in the boat must act as one,\n"
            + "which meant that we incessantly worked to keep each movement in the boat synchronized. On\n"
            + "an individual basis, we still worked toward group goals through weightlifting and land-rowing. My\n"
            + "experience as a marketing research team leader also helped me to learn the role of \"team\n"
            + "player.\" I viewed my position as that of group leader and of group member. I ensured that\n"
            + "everyone in the group had equal opportunity to contribute, maintained excellent communication\n"
            + "among group members, and coordinated their energies toward reaching our team's goal.\n"
            + "78.Are you a goal-oriented person?\n"
            + "79.Tell me about some of your recent goals and what you did to achieve them. Give me an\n"
            + "example of an important goal which you had set in the past and tell me about your success in\n"
            + "reaching it.\n"
            + "As a senior in high school, my goal was to attend college and play college golf. But I was nowhere\n"
            + "near the player I needed to be to play or even get on the team. So over that summer I worked on. 1point3acres\n"
            + "my golf game to the point where I won almost every tournament I entered. I spent every hour I\n"
            + "had during the day to make myself a better all-around player. I eventually walked on my freshmen\n"
            + "year and was exempted from qualifying because I played so well in my first outing.. From 1point 3acres bbs\n"
            + "80.What major problem have you had to deal with recently?. 1point3acres\n"
            + "81.Do you handle pressure well?\n"
            + "82.How much training do you think you’ ll need to become a productive employee?\n"
            + "My background has been focused on preparing me for the financial consulting industry, so I can\n"
            + "be productive right away. I already have obtained the educational credentials and skills to allow\n"
            + "me to become an immediate asset to Merrill Lynch. After interning for a semester, I am well\n"
            + "aware of the shared beliefs of the organization and its corporate values. I already have a very\n"
            + "good working knowledge of the financial consulting business. I am confident of my ability to get\n"
            + "up to speed quickly in any assignment with which I'm not familiar.\n"
            + "83.Why do you want to work in the _____ industry?. check 1point3acres for more.\n"
            + "84.Are you willing to travel? How much?\n"
            + "I am more than willing to travel. I understand the importance of going above and beyond the call\n"
            + "of duty to satisfy customer requests is sometimes required and that Merrill Lynch's customer\n"
            + "focus belief means that travel is expected in some circumstances. I am willing to make this\n"
            + "commitment to do whatever it takes to develop that long-term relationship with a small business\n"
            + "or client. It is only through this relationship that loyalty can be maintained and financial gains and\n"
            + "growth can occur for both the client and Merrill Lynch. It is my understanding from other\n"
            + "financial consultants that I have interviewed at Merrill Lynch that this occurs maybe one or two\n"
            + "times a month.\n"
            + "85.Is money important to you?\n"
            + "Which is more important to you, the job itself or your salary?\n"
            + "A salary commensurate with my experience and skills is important, but it's only one piece of the\n"
            + "package. Many other elements go into making up a compensation package, but more importantly,\n"
            + "it's critical to me to enjoy what I'm doing, fit into the corporate culture, and feel I'm making a\n"
            + "genuine contribution.\n"
            + "86.How much money do you need to make to be happy?\n"
            + "What level of compensation would it take to make you happy?\n"
            + "I am not depending on money to make me happy. What makes me happy is having a satisfying\n"
            + "job that provides challenge and new situations daily.\n"
            + "87.Tell of a time when you worked with a colleague who was not completing his or her share of\n"
            + "the work. Who, if anyone, did you tell or talk to about it? Did the manager take any steps to\n"
            + "correct your colleague? Did you agree or disagree with the manager's actions?. From 1point 3acres bbs\n"
            + "During a group project in college, we had one member who would do no work whatsoever. The. 1point3acres\n"
            + "project was to compare and contrast four companies in a single industry, so his work was vital.\n"
            + "We first discussed the situation and asked for the bare-bones minimum of what we needed from\n"
            + "him. We got just below that. As a result we as a group went to the professor and told her our\n"
            + "situation -- not expecting or requesting action -- just informing her the situation we were dealing\n"
            + "with. Then we as a group split up the non-contributor's work, and completed our work\n"
            + "collectively on his share. In phase two in which we analyzed the information and reported how\n"
            + "each of our companies fared compared to the others, we did not get a paper from the group\n"
            + "member. As a result, we told the teacher that we had our work done, and were willing to do the\n"
            + "extra paper but that we would rather spend time polishing our own work, and not picking up\n"
            + "slack. She agreed and said to focus on the three companies we had compiled the most info on\n"
            + "while not entirely neglecting the fourth. The papers came out very well, but were understandably\n"
            + "weak when comparing the fourth company. The professor understood, and we received the\n"
            + "grades we deserved. I was pleased with our teamwork and the way we handled the situation.\n"
            + "88. Describe a situation in which you had to arrive at a compromise or guide others to a\n"
            + "compromise.. From 1point 3acres bbs\n"
            + "My first semester in college, I was a political-science major. My introductory government class. check 1point3acres for more.\n"
            + "professor had a differing political view then I. We disagreed on everything, and many classes\n"
            + "were filled with criticizing each others' view. However, on one test I answered a question with the\n"
            + "view I believe in, and she marked it wrong. So I asked her how an opinion can be wrong, and she\n"
            + "said because her opinion is the way she taught it in class. I pointed out that my answer showed I\n"
            + "understood the concepts of the question. She agreed, and I also agreed not be so combative in\n"
            + "answers on tests. Compromise is the key to problem resolution.";
//        System.out.println(s);
//        System.out.println(s.replace("\n","  "));
      s =  s.replace("The. 1point3acres","  ");
      s =  s.replace("From 1point 3acres bbs","  ");
      s =  s.replace("check 1point3acres for more.","  ");
      s =  s.replace("1point","  ");
      s =  s.replace("\n","  ");
        String r = s.replaceAll("(\\d+)",  "\r\n\r\n$1");
        System.out.println(r);


    }
}
